model:
  path: ./models/hand_landmarker.task

camera:
  window_handle: "Reachy Mini | Vision and Tracking"
  index: 0
  width: 1280
  height: 720
  target_fps: 30

websocket:
  port: 8765
  host: "0.0.0.0"
